<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net472</TargetFrameworks>
    <RootNamespace>Atata.Xunit</RootNamespace>
    <Version>4.0.0</Version>
    <Description>
C#/.NET library that integrates Atata with xUnit v3.

Atata.Xunit.v3 on GitHub: https://github.com/atata-framework/atata-xunit-v3
Atata Framework documentation: https://atata.io/

The package targets .NET 8.0 and .NET Framework 4.7.2.
    </Description>
    <RepositoryUrl>https://github.com/atata-framework/atata-xunit-v3</RepositoryUrl>
    <PackageId>Atata.Xunit.v3</PackageId>
    <PackageTags>atata automation testing test xunit</PackageTags>
    <PackageReleaseNotes>Changelog: https://github.com/atata-framework/atata-xunit-v3/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/atata-framework/atata-xunit-v3</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Atata" Version="4.0.0" />
    <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="4.0.0" />
  </ItemGroup>

</Project>
